run_name = "dense-baseline"
num_trials = 1
seed = 1234

[model]
vocab_size = 50304
num_layers = 12
model_dim = 768
mlp_type = "dense"
mlp_ratio = 4
num_experts = 1
top_k = 1
normalize_topk = true
moe_backend = "loop"

[training]
sequence_length = 1024
global_batch_tokens = 524288
microbatch_sequences = 64
validation_tokens = 10485760
total_steps = 3250
cooldown_fraction = 0.7
training_shard_pattern = "data/fineweb10B/fineweb_train_*.bin"
validation_shard_pattern = "data/fineweb10B/fineweb_val_*.bin"

[optimizers.adamw]
group_lrs = [0.7, 0.004, 0.015]
betas = [0.8, 0.95]
eps = 1e-10
weight_decay = 0.001
fused = true

[optimizers.muon]
lr = 0.025
weight_decay = 0.05
mu = 0.95
